# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 9000

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://192.168.33.11:3306/spring-security-demo
    username: root
    password: Abc@123456
    driver-class-name: com.mysql.jdbc.Driver 

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh